### ISSUE TITLE
Desktop discussion

### ISSUE THREAD

**Issue by imrn** [rodlie/draco#1]
Thank's for the effort.

I'd like to see it grow as a set of loosely coupled set of apps, playing
nicely with each other. But they should also run just fine when used alone.

Main functionality/apps can be defined narrowly:

- Filemanager with desktop management capabilities.
https://github.com/rodlie/qtfm/issues/100

- Panel: Application menus/launcher/taskbar/etc.. That is only an
application/window handling thing.

- Multi Display Management: I currently use xfce4-display-settings which
allows convenient physical placement of displays. Of course I'd expect
panel and desktop handling fm to be compatible with multihead configurations.

My understanding of "desktop" is nothing more than that.
No to eyecaddy things. Just black background. It is beautiful. ;)

**Comment by rodlie** [comment]
The DE will have the following components:

* draco-desktop
  * the desktop and panel, can be started/used from any WM/setup
* start-draco-desktop
  * the "DE"
* draco-desktop-settings
  * settings for desktop, panel etc
* draco-desktop-xsettings
  * X11/xrandr settings

That's it :) I want to keep it simple. Note that the desktop will require that qtfm-* is installed for some functions (storage etc). Everything related to power management is handled by (optional) powerkit.

**Comment by imrn** [comment]
Looking for to use it soon. ;)

> draco-desktop
> the desktop and panel, can be started/used from any WM/setup

Can you elaborate? Are you planning something
which provides combined functionality of "qtfm --desktop" + panel
in a single executable?

Or a seperate panel and a seperate fm providing/managing desktop files/icons?

> draco-desktop-settings
>    settings for desktop, panel etc

Wouldn't it be nice for each executable to manage its own settings for
standalone operation?

**Comment by FrostKnight** [comment]
I didn't even know about this repo... I have a few questions: one is this fork going to be almost as lightweight as the Lumina Desktop? two when will it be released? and three, what are the differences as a whole? Ps, i love Lumina-Desktop and your powerkit app. ;)
I wish you well on your new modular desktop. If possible, make it even more lightweight by default, :)
I use Lumina-desktop + powerkit as of now on my OS: Hyperbola, GNU/Linux-Libre
Everything works lovely on it by the way.  
Lumina and Trinity Desktop are the only qt desktops that don't suck imo. But Lumina is far better.

**Comment by rodlie** [comment]
@FrostKnight :

This is a stripped-down fork of Lumina (for Linux). It will only include the core components for a working desktop environment, the rest is up to the user. It will include proper power management (through powerkit) and other (free)desktop features (through qtfm). Draco will also use Openbox instead of Fluxbox, for improved application compatibility (and other features).

It's still not ready, I hope to have something usable this week if possible (depends on "real life").

Great to hear that you like powerkit, it was originally made for Lumina (but since they (Lumina) was not interested in it I just made it universal).

**Comment by FrostKnight** [comment]
Ah, okay so correct me if I am wrong, you are saying it will be based off of openbox, and it will only include the core stuff... does that mean, no panel by default or in geneal?
ps, yeah, I do love powerkit, unlike xfce4's powermanager, yours is much lighter on resources and is less buggy too.  

I don't know if I told you this, but I think that, QT desktops, with the exception of Lumina, Trinity and hopefully yours, suck in my opinion. So it was refreshing to find Lumina, and also to find powerkit and yes, I searched Lumina's issue tracker to find if there was a power manager for Lumina, that's how I found you. :)

I hope your qt based desktop will be as good if not better than Lumina.  If its not as good, I may stick with Lumina though. ;p
I am curious though, why they were not interested in your powerkit, aka Lumina.

**Comment by rodlie** [comment]
The desktop and panel is part of the core. My goal is to make/maintain a light, stable "classic" desktop.

Regarding powerkit and Lumina: I have made several applications aimed at Lumina to enhance the user experience, but Lumina don't want anything using D-Bus etc, they only focus on FreeBSD/Trident.... This is one of the reasons for the fork, I want the best user experience, not a mediocre experience because the developers have "issues" against Linux, D-Bus etc etc. Note I don't have anything against the developers or the project (Lumina), we just have different goals.

**Comment by FrostKnight** [comment]
Oh it is part of the core? Cool! I am glad to hear it, I hope you will achieve that goal.

In, Lumina you can run without using over 150MB, will you be aiming for less than 100MB? As a default I mean. :)

Lumina is blazing fast, I hope yours will be even better.

 Do you plan to accept donations in the future by the way? or are you doing this for the same reasons Ublock Origin and Nano Adblocker are? Aka, wanting complete control over the project and not owing anyone anything/doing it because you want to. 
Anywho, I look forward to testing your release whether it beta or stable. :)

**Comment by FrostKnight** [comment]
What are the xcb files for anyways?

**Comment by FrostKnight** [comment]
Just going to let you know, the below helped  me to compile draco from source, for my arch based distro. It works for Hyperbola, not sure if it works for archlinux as a whole. But yeah, its your commands for your slack build:
mkdir build && cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib64 -DCMAKE_INSTALL_MANDIR=/usr/man -DCMAKE_INSTALL_DOCDIR=/usr/doc -DCMAKE_BUILD_TYPE=Release ..
make
sudo make install

I immediately noticed that when I booted into draco desktop that most applications don't open though, but I absolutely love the amount of ram usage. It is less than 100mb! :)
And yea, I realize its not ready yet. just letting you know that your slackbuild instructions worked for my arch based distro.

Anyways, that's my feedback.

**Comment by rodlie** [comment]
Stuff don't work at the moment due to the transition to cmake, merging powerkit with draco etc, etc, will be more usable by the end of the weekend.

**Comment by FrostKnight** [comment]
Yep, still, it looks very nice and I bet it will be more lightweight even then lumina. :)

When released I mean... ;o

**Comment by FrostKnight** [comment]
Been testing it a bit, almost every commit you've made.  But I wondered, for some reason, my utox app cannot be used with the draco desktop panel, (same with Lumina) unless, I have no account. Aka, when my utox account has no password, it is able to work, otherwise the utox icon and its functionality are null and void

I reported bug to Lumina, and they were not willing to fix it saying, ask utox. As for utox, pretty much the same issue.  

That aside, I am eager to see the beta of Draco Desktop. 

PS, only reason I commented here so many times, is because I didn't know where I could give you feedback, etc...

Hope I didn't cause any problems.

**Comment by rodlie** [comment]
can you post the desktop file for utox?

**Comment by rodlie** [comment]
I did test uTox and the tray stuff is broken, but this is on uTox (found a lot of related issues regarding the tray on uTox). Other than that I don't know, I don't use uTox (never heard of it before now)

**Comment by FrostKnight** [comment]
Yep, although, even if I were to comment about this to utox, I probably should wait till your desktop is stable. Otherwise, they will probably not do much about it. That being said, thank you for checking on it.

**Comment by rodlie** [comment]
I tried several things in utox (source code), but I was not able to get the tray running. I can look at it again at a later time, for now I need to get Draco done.

**Comment by FrostKnight** [comment]
Sounds like a good idea. No problem man.

**Comment by imrn** [comment]
Thanks for all of the effort. But I still think that core desktop function is just a lean panel, desktop file/shortcut management and a good file manager. That's all. I really mean it. I could not understand why it is so difficult to have just that. All of the desktop environments have many bells and whistles but they all lack robust functionality at the core level. While opening this issue I had this in my mind. Of course I would not mind optional accesories but they cause missing the core target by sucking the available man power and thus they all became unsuccessful in the long run. I'd like to see draco fullfilng the core first.

Let me give a random usecase for my laptop:
I never use hibernation. Suspend is just "echo mem > /sys/power/state" shell script with a shortcut on the panel. I compiled my kernel with conservative governor, and set all powersaving options for the cpu, pci bus, acpi, etc. This is all for my power management setup and no bell/whistle can beat it. Got the point?

**Comment by imrn** [comment]
Plus multi head/display support.

**Comment by rodlie** [comment]
Then Draco is not for you. I want a functional desktop, that means storage and power support as a minimum.

**Comment by rodlie** [comment]
btw, you can run just the desktop (and panel):

``/usr/libexec/org.dracolinux.Desktop --nostartup``

Some feature may not work of course.

**Comment by FrostKnight** [comment]
This is a wonderful desktop rodlie, I very much appreciate it.  I know its prolly only beta right now, but its very nice. I know you forked it from Lumina, but I much like the minimal effect. that your giving it. :)

**Comment by rodlie** [comment]
The project as a hole will be gpl2+, but it includes BSD-3, LGPL 2.1+ and GPL-2+.

Yes, it's a fork. I was a contributor to Lumina, but my vision of the DE was not shared with Lumina, so I first started developing tools around Lumina to add what I needed, but due to many bugs in the core , slow development etc, and wanting better integration I just had to fork (Lumina does not want anything to do with D-Bus or "Linux developed" software). Also the roadmap for Lumina v2 (if they ever get there) is not something I want or share.

Most of the features I want or need in a desktop has been added as open issues here on github, After that the desktop will move over to maintenance mode, just fixing bugs. I might add a small feature here and there, but the desktop should been seen as complete by v1, I want to use the desktop myself and do other work ;)

**Comment by imrn** [comment]
> Then Draco is not for you. I want a functional desktop, that means storage
> and power support as a minimum.

Note that, MS Windows users will not switch to your desktop in the foreseenable future. Your potential users are tech savy linux/bsd people who generally dislike bells/whistles and who want real work done. As a final question:

Do you plan to provide
1) Standalone configurable lean panel (similar to tint2)
2) "qtfm --desktop" mode

**Comment by rodlie** [comment]
Talk for yourself, most "power" users I know want stuff to work so they can get work done.

1. No.
2. No.

**Comment by imrn** [comment]
> Talk for yourself, most "power" users I know want stuff to work so they can
> get work done.
>
> 1. No.
> 2. No.

Thanks anyway. I wish, I've heard this earlier.

**Comment by FrostKnight** [comment]
> The project as a hole will be gpl2+, but it includes BSD-3, LGPL 2.1+ and GPL-2+.
> 
> Yes, it's a fork. I was a contributor to Lumina, but my vision of the DE was not shared with Lumina, so I first started developing tools around Lumina to add what I needed, but due to many bugs in the core , slow development etc, and wanting better integration I just had to fork (Lumina does not want anything to do with D-Bus or "Linux developed" software). Also the roadmap for Lumina v2 (if they ever get there) is not something I want or share.
> 
> Most of the features I want or need in a desktop has been added as open issues here on github, After that the desktop will move over to maintenance mode, just fixing bugs. I might add a small feature here and there, but the desktop should been seen as complete by v1, I want to use the desktop myself and do other work ;)

Either way, we need less bloated desktops like Lumina and Draco. 
 I do wonder what v2 of Lumina must look like... either way though, thanks for giving me an alternative to XFCE4-desktop, LXDE and Trinity Desktop. I have no doubt yours is lighter even then Lumina let alone those other ones which eat up so much ram/battery life.
